# Generated by Django 5.0 on 2023-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('explain', models.CharField(max_length=500)),
                ('img', models.ImageField(default='photo/no_image.png', upload_to='photo/')),
            ],
        ),
    ]
